/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    Guide: typeof import('./src/components/AppNavigation.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
