/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CCartView': RouteRecordInfo<'/CCartView', '/CCartView', Record<never, never>, Record<never, never>>,
    '/CHomeView': RouteRecordInfo<'/CHomeView', '/CHomeView', Record<never, never>, Record<never, never>>,
    '/COrdersView': RouteRecordInfo<'/COrdersView', '/COrdersView', Record<never, never>, Record<never, never>>,
    '/MLoginView': RouteRecordInfo<'/MLoginView', '/MLoginView', Record<never, never>, Record<never, never>>,
    '/MOrderView': RouteRecordInfo<'/MOrderView', '/MOrderView', Record<never, never>, Record<never, never>>,
    '/MProductView': RouteRecordInfo<'/MProductView', '/MProductView', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/CCartView.vue': {
      routes: '/CCartView'
      views: never
    }
    'src/pages/CHomeView.vue': {
      routes: '/CHomeView'
      views: never
    }
    'src/pages/COrdersView.vue': {
      routes: '/COrdersView'
      views: never
    }
    'src/pages/MLoginView.vue': {
      routes: '/MLoginView'
      views: never
    }
    'src/pages/MOrderView.vue': {
      routes: '/MOrderView'
      views: never
    }
    'src/pages/MProductView.vue': {
      routes: '/MProductView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
